<?xml version="1.0" encoding="UTF-8"?>
<!--
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    @name syllab.xsl
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    @version 002
    @date 2015-04-20
    @since 2015-04-19
    @xslt 2.0 (avec oXygen utiliser > Saxon HE 9)
    @autor Emmanuel Château emchateau@laposte.net
    @rmq traiter la variable $syllabary dans un document externe (cf. ex)
    @rmq les deux passes permettent d’autres traitements préparatoires éventuels
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0"
    xpath-default-namespace="http://www.tei-c.org/ns/1.0"
    xmlns="http://www.tei-c.org/ns/1.0">

    <xsl:output indent="yes" method="xml" encoding="UTF-8"/>

    <xsl:strip-space elements="*"/>

    <xsl:variable name="syllabary">
        <entry>
            <syllab>DURU₅</syllab>
            <indice>579</indice>
        </entry>
        <entry>
            <syllab>a₄</syllab>
            <indice>589</indice>
        </entry>
        <entry>
            <syllab>ì</syllab>
            <indice>396</indice>
        </entry>
        <entry>
            <syllab>’ì</syllab>
            <indice>396</indice>
        </entry>
        <entry>
            <syllab>(d)</syllab>
            <indice>13</indice>
        </entry>
        <entry>
            <syllab>(gi)</syllab>
            <indice>85</indice>
        </entry>
        <entry>
            <syllab>(giš)</syllab>
            <indice>296</indice>
        </entry>
        <entry>
            <syllab>(I)</syllab>
            <indice>480</indice>
        </entry>
        <entry>
            <syllab>(i₇)</syllab>
            <indice>579a</indice>
        </entry>
        <entry>
            <syllab>(ki)</syllab>
            <indice>461</indice>
        </entry>
        <entry>
            <syllab>(kuš)</syllab>
            <indice>7</indice>
        </entry>
        <entry>
            <syllab>(munus)</syllab>
            <indice>554</indice>
        </entry>
        <entry>
            <syllab>(túg)</syllab>
            <indice>536</indice>
        </entry>
        <entry>
            <syllab>(uru)</syllab>
            <indice>38</indice>
        </entry>
        <entry>
            <syllab>a</syllab>
            <indice>579</indice>
        </entry>
        <entry>
            <syllab>A</syllab>
            <indice>579</indice>
        </entry>
        <entry>
            <syllab>á'</syllab>
            <indice>398</indice>
        </entry>
        <entry>
            <syllab>á’</syllab>
            <indice>398</indice>
        </entry>
        <entry>
            <syllab>AB</syllab>
            <indice>128</indice>
        </entry>
        <entry>
            <syllab>ab</syllab>
            <indice>128</indice>
        </entry>
        <entry>
            <syllab>ÁB</syllab>
            <indice>420</indice>
        </entry>
        <entry>
            <syllab>AD</syllab>
            <indice>145</indice>
        </entry>
        <entry>
            <syllab>ad</syllab>
            <indice>145</indice>
        </entry>
        <entry>
            <syllab>ag</syllab>
            <indice>97</indice>
        </entry>
        <entry>
            <syllab>AGA</syllab>
            <indice>347</indice>
        </entry>
        <entry>
            <syllab>AGRIG</syllab>
            <indice>452</indice>
        </entry>
        <entry>
            <syllab>ah</syllab>
            <indice>398</indice>
        </entry>
        <entry>
            <syllab>ak</syllab>
            <indice>97</indice>
        </entry>
        <entry>
            <syllab>al</syllab>
            <indice>298</indice>
        </entry>
        <entry>
            <syllab>am</syllab>
            <indice>170</indice>
        </entry>
        <entry>
            <syllab>ÀM</syllab>
            <indice>579b</indice>
        </entry>
        <entry>
            <syllab>am₇</syllab>
            <indice>383</indice>
        </entry>
        <entry>
            <syllab>AMAR</syllab>
            <indice>437</indice>
        </entry>
        <entry>
            <syllab>an</syllab>
            <indice>13</indice>
        </entry>
        <entry>
            <syllab>AN</syllab>
            <indice>13</indice>
        </entry>
        <entry>
            <syllab>ANŠE</syllab>
            <indice>208</indice>
        </entry>
        <entry>
            <syllab>ap</syllab>
            <indice>128</indice>
        </entry>
        <entry>
            <syllab>APIN</syllab>
            <indice>56</indice>
        </entry>
        <entry>
            <syllab>aq</syllab>
            <indice>97</indice>
        </entry>
        <entry>
            <syllab>ar</syllab>
            <indice>451</indice>
        </entry>
        <entry>
            <syllab>as</syllab>
            <indice>131</indice>
        </entry>
        <entry>
            <syllab>aš</syllab>
            <indice>1</indice>
        </entry>
        <entry>
            <syllab>aṣ</syllab>
            <indice>131</indice>
        </entry>
        <entry>
            <syllab>ás</syllab>
            <indice>435</indice>
        </entry>
        <entry>
            <syllab>áš</syllab>
            <indice>435</indice>
        </entry>
        <entry>
            <syllab>às</syllab>
            <indice>1</indice>
        </entry>
        <entry>
            <syllab>ASAL</syllab>
            <indice>44</indice>
        </entry>
        <entry>
            <syllab>AŠGAB</syllab>
            <indice>104</indice>
        </entry>
        <entry>
            <syllab>at</syllab>
            <indice>145</indice>
        </entry>
        <entry>
            <syllab>aṭ</syllab>
            <indice>145</indice>
        </entry>
        <entry>
            <syllab>az</syllab>
            <indice>131</indice>
        </entry>
        <entry>
            <syllab>ba</syllab>
            <indice>5</indice>
        </entry>
        <entry>
            <syllab>BA</syllab>
            <indice>5</indice>
        </entry>
        <entry>
            <syllab>BABBAR</syllab>
            <indice>381</indice>
        </entry>
        <entry>
            <syllab>BÀD</syllab>
            <indice>152</indice>
        </entry>
        <entry>
            <syllab>BANDA</syllab>
            <indice>439</indice>
        </entry>
        <entry>
            <syllab>bar</syllab>
            <indice>74</indice>
        </entry>
        <entry>
            <syllab>BAR</syllab>
            <indice>74</indice>
        </entry>
        <entry>
            <syllab>be</syllab>
            <indice>69</indice>
        </entry>
        <entry>
            <syllab>bé</syllab>
            <indice>214</indice>
        </entry>
        <entry>
            <syllab>BI</syllab>
            <indice>214</indice>
        </entry>
        <entry>
            <syllab>bi</syllab>
            <indice>214</indice>
        </entry>
        <entry>
            <syllab>bí</syllab>
            <indice>172</indice>
        </entry>
        <entry>
            <syllab>bíl</syllab>
            <indice>173</indice>
        </entry>
        <entry>
            <syllab>bu</syllab>
            <indice>371</indice>
        </entry>
        <entry>
            <syllab>da</syllab>
            <indice>335</indice>
        </entry>
        <entry>
            <syllab>DA</syllab>
            <indice>335</indice>
        </entry>
        <entry>
            <syllab>DAH</syllab>
            <indice>169</indice>
        </entry>
        <entry>
            <syllab>dam</syllab>
            <indice>557</indice>
        </entry>
        <entry>
            <syllab>DAM</syllab>
            <indice>557</indice>
        </entry>
        <entry>
            <syllab>dan</syllab>
            <indice>322</indice>
        </entry>
        <entry>
            <syllab>de</syllab>
            <indice>457</indice>
        </entry>
        <entry>
            <syllab>di</syllab>
            <indice>457</indice>
        </entry>
        <entry>
            <syllab>DI</syllab>
            <indice>457</indice>
        </entry>
        <entry>
            <syllab>dí</syllab>
            <indice>396</indice>
        </entry>
        <entry>
            <syllab>DIB</syllab>
            <indice>537</indice>
        </entry>
        <entry>
            <syllab>DIDLI</syllab>
            <indice>2</indice>
        </entry>
        <entry>
            <syllab>DÍM</syllab>
            <indice>440</indice>
        </entry>
        <entry>
            <syllab>DIM₄</syllab>
            <indice>60</indice>
        </entry>
        <entry>
            <syllab>din</syllab>
            <indice>465</indice>
        </entry>
        <entry>
            <syllab>DINGIR</syllab>
            <indice>13</indice>
        </entry>
        <entry>
            <syllab>DU</syllab>
            <indice>206</indice>
        </entry>
        <entry>
            <syllab>du</syllab>
            <indice>206</indice>
        </entry>
        <entry>
            <syllab>DÙ</syllab>
            <indice>230</indice>
        </entry>
        <entry>
            <syllab>DU₅</syllab>
            <indice>595</indice>
        </entry>
        <entry>
            <syllab>DU₆</syllab>
            <indice>459</indice>
        </entry>
        <entry>
            <syllab>DU₇</syllab>
            <indice>441</indice>
        </entry>
        <entry>
            <syllab>DU₈</syllab>
            <indice>167</indice>
        </entry>
        <entry>
            <syllab>dub</syllab>
            <indice>138</indice>
        </entry>
        <entry>
            <syllab>DUB</syllab>
            <indice>138</indice>
        </entry>
        <entry>
            <syllab>DUG</syllab>
            <indice>309</indice>
        </entry>
        <entry>
            <syllab>DUH</syllab>
            <indice>167</indice>
        </entry>
        <entry>
            <syllab>DUMU</syllab>
            <indice>144</indice>
        </entry>
        <entry>
            <syllab>E</syllab>
            <indice>308</indice>
        </entry>
        <entry>
            <syllab>e</syllab>
            <indice>308</indice>
        </entry>
        <entry>
            <syllab>é</syllab>
            <indice>324</indice>
        </entry>
        <entry>
            <syllab>É</syllab>
            <indice>324</indice>
        </entry>
        <entry>
            <syllab>È</syllab>
            <indice>381a</indice>
        </entry>
        <entry>
            <syllab>eb</syllab>
            <indice>535</indice>
        </entry>
        <entry>
            <syllab>ed</syllab>
            <indice>334</indice>
        </entry>
        <entry>
            <syllab>EDIN</syllab>
            <indice>168</indice>
        </entry>
        <entry>
            <syllab>EGIR</syllab>
            <indice>209</indice>
        </entry>
        <entry>
            <syllab>eh</syllab>
            <indice>398</indice>
        </entry>
        <entry>
            <syllab>ek</syllab>
            <indice>80</indice>
        </entry>
        <entry>
            <syllab>el</syllab>
            <indice>564</indice>
        </entry>
        <entry>
            <syllab>ELAM</syllab>
            <indice>433</indice>
        </entry>
        <entry>
            <syllab>em</syllab>
            <indice>399</indice>
        </entry>
        <entry>
            <syllab>EME</syllab>
            <indice>32</indice>
        </entry>
        <entry>
            <syllab>EN</syllab>
            <indice>99</indice>
        </entry>
        <entry>
            <syllab>en</syllab>
            <indice>99</indice>
        </entry>
        <entry>
            <syllab>en₆</syllab>
            <indice>148</indice>
        </entry>
        <entry>
            <syllab>ENSI₂</syllab>
            <indice>295</indice>
        </entry>
        <entry>
            <syllab>ep</syllab>
            <indice>535</indice>
        </entry>
        <entry>
            <syllab>eq</syllab>
            <indice>80</indice>
        </entry>
        <entry>
            <syllab>er</syllab>
            <indice>232</indice>
        </entry>
        <entry>
            <syllab>ERIN₂</syllab>
            <indice>393</indice>
        </entry>
        <entry>
            <syllab>es</syllab>
            <indice>296</indice>
        </entry>
        <entry>
            <syllab>eš</syllab>
            <indice>472</indice>
        </entry>
        <entry>
            <syllab>ÉŠ</syllab>
            <indice>536</indice>
        </entry>
        <entry>
            <syllab>ÈŠ</syllab>
            <indice>128</indice>
        </entry>
        <entry>
            <syllab>eš₁₅</syllab>
            <indice>212</indice>
        </entry>
        <entry>
            <syllab>et</syllab>
            <indice>334</indice>
        </entry>
        <entry>
            <syllab>eṭ</syllab>
            <indice>334</indice>
        </entry>
        <entry>
            <syllab>ez</syllab>
            <indice>296</indice>
        </entry>
        <entry>
            <syllab>ga</syllab>
            <indice>319</indice>
        </entry>
        <entry>
            <syllab>GA</syllab>
            <indice>319</indice>
        </entry>
        <entry>
            <syllab>GÁ</syllab>
            <indice>233</indice>
        </entry>
        <entry>
            <syllab>GAB</syllab>
            <indice>167</indice>
        </entry>
        <entry>
            <syllab>GAD</syllab>
            <indice>90</indice>
        </entry>
        <entry>
            <syllab>GAL</syllab>
            <indice>343</indice>
        </entry>
        <entry>
            <syllab>gan</syllab>
            <indice>143</indice>
        </entry>
        <entry>
            <syllab>GAN</syllab>
            <indice>143</indice>
        </entry>
        <entry>
            <syllab>GÁN</syllab>
            <indice>105</indice>
        </entry>
        <entry>
            <syllab>GAR</syllab>
            <indice>597</indice>
        </entry>
        <entry>
            <syllab>GÀR</syllab>
            <indice>333</indice>
        </entry>
        <entry>
            <syllab>GAZ</syllab>
            <indice>192</indice>
        </entry>
        <entry>
            <syllab>ge</syllab>
            <indice>85</indice>
        </entry>
        <entry>
            <syllab>GEME₂</syllab>
            <indice>558</indice>
        </entry>
        <entry>
            <syllab>GEŠTIN</syllab>
            <indice>210</indice>
        </entry>
        <entry>
            <syllab>gi</syllab>
            <indice>85</indice>
        </entry>
        <entry>
            <syllab>GI</syllab>
            <indice>85</indice>
        </entry>
        <entry>
            <syllab>GI₄</syllab>
            <indice>326</indice>
        </entry>
        <entry>
            <syllab>GÍD</syllab>
            <indice>371</indice>
        </entry>
        <entry>
            <syllab>GIDRI</syllab>
            <indice>295</indice>
        </entry>
        <entry>
            <syllab>GIM</syllab>
            <indice>440</indice>
        </entry>
        <entry>
            <syllab>gim</syllab>
            <indice>440</indice>
        </entry>
        <entry>
            <syllab>gir</syllab>
            <indice>346</indice>
        </entry>
        <entry>
            <syllab>GÍR</syllab>
            <indice>10</indice>
        </entry>
        <entry>
            <syllab>GÌR</syllab>
            <indice>444</indice>
        </entry>
        <entry>
            <syllab>GIŠ</syllab>
            <indice>296</indice>
        </entry>
        <entry>
            <syllab>GU</syllab>
            <indice>559</indice>
        </entry>
        <entry>
            <syllab>gu</syllab>
            <indice>559</indice>
        </entry>
        <entry>
            <syllab>GÚ</syllab>
            <indice>106</indice>
        </entry>
        <entry>
            <syllab>GU₄</syllab>
            <indice>297</indice>
        </entry>
        <entry>
            <syllab>GUB</syllab>
            <indice>206</indice>
        </entry>
        <entry>
            <syllab>GUR</syllab>
            <indice>111</indice>
        </entry>
        <entry>
            <syllab>gur</syllab>
            <indice>111</indice>
        </entry>
        <entry>
            <syllab>ha</syllab>
            <indice>589</indice>
        </entry>
        <entry>
            <syllab>HA</syllab>
            <indice>589</indice>
        </entry>
        <entry>
            <syllab>HA₆</syllab>
            <indice>346</indice>
        </entry>
        <entry>
            <syllab>hal</syllab>
            <indice>2</indice>
        </entry>
        <entry>
            <syllab>HAR</syllab>
            <indice>401</indice>
        </entry>
        <entry>
            <syllab>har</syllab>
            <indice>401</indice>
        </entry>
        <entry>
            <syllab>he</syllab>
            <indice>396</indice>
        </entry>
        <entry>
            <syllab>HÉ</syllab>
            <indice>143</indice>
        </entry>
        <entry>
            <syllab>hi</syllab>
            <indice>396</indice>
        </entry>
        <entry>
            <syllab>HI</syllab>
            <indice>396</indice>
        </entry>
        <entry>
            <syllab>hu</syllab>
            <indice>78</indice>
        </entry>
        <entry>
            <syllab>húb</syllab>
            <indice>88</indice>
        </entry>
        <entry>
            <syllab>HUN</syllab>
            <indice>536</indice>
        </entry>
        <entry>
            <syllab>i</syllab>
            <indice>142</indice>
        </entry>
        <entry>
            <syllab>I</syllab>
            <indice>142</indice>
        </entry>
        <entry>
            <syllab>ì</syllab>
            <indice>231</indice>
        </entry>
        <entry>
            <syllab>Ì</syllab>
            <indice>231</indice>
        </entry>
        <entry>
            <syllab>í'</syllab>
            <indice>398</indice>
        </entry>
        <entry>
            <syllab>I₇</syllab>
            <indice>579a</indice>
        </entry>
        <entry>
            <syllab>ia</syllab>
            <indice>192</indice>
        </entry>
        <entry>
            <syllab>ib</syllab>
            <indice>535</indice>
        </entry>
        <entry>
            <syllab>id</syllab>
            <indice>334</indice>
        </entry>
        <entry>
            <syllab>IDIGNA</syllab>
            <indice>74b</indice>
        </entry>
        <entry>
            <syllab>ig</syllab>
            <indice>80</indice>
        </entry>
        <entry>
            <syllab>IGI</syllab>
            <indice>449</indice>
        </entry>
        <entry>
            <syllab>ih</syllab>
            <indice>398</indice>
        </entry>
        <entry>
            <syllab>ik</syllab>
            <indice>80</indice>
        </entry>
        <entry>
            <syllab>il</syllab>
            <indice>205</indice>
        </entry>
        <entry>
            <syllab>ÍL</syllab>
            <indice>320</indice>
        </entry>
        <entry>
            <syllab>ILLAT</syllab>
            <indice>466</indice>
        </entry>
        <entry>
            <syllab>ILLURU</syllab>
            <indice>68</indice>
        </entry>
        <entry>
            <syllab>im</syllab>
            <indice>399</indice>
        </entry>
        <entry>
            <syllab>in</syllab>
            <indice>148</indice>
        </entry>
        <entry>
            <syllab>INANNA</syllab>
            <indice>103</indice>
        </entry>
        <entry>
            <syllab>ip</syllab>
            <indice>535</indice>
        </entry>
        <entry>
            <syllab>iq</syllab>
            <indice>80</indice>
        </entry>
        <entry>
            <syllab>ir</syllab>
            <indice>232</indice>
        </entry>
        <entry>
            <syllab>ÌR</syllab>
            <indice>50</indice>
        </entry>
        <entry>
            <syllab>IR₁₁</syllab>
            <indice>50a</indice>
        </entry>
        <entry>
            <syllab>is</syllab>
            <indice>296</indice>
        </entry>
        <entry>
            <syllab>iš</syllab>
            <indice>212</indice>
        </entry>
        <entry>
            <syllab>iṣ</syllab>
            <indice>296</indice>
        </entry>
        <entry>
            <syllab>ìs</syllab>
            <indice>128</indice>
        </entry>
        <entry>
            <syllab>iš₈</syllab>
            <indice>361</indice>
        </entry>
        <entry>
            <syllab>IŠKUR</syllab>
            <indice>399</indice>
        </entry>
        <entry>
            <syllab>it</syllab>
            <indice>334</indice>
        </entry>
        <entry>
            <syllab>iṭ</syllab>
            <indice>334</indice>
        </entry>
        <entry>
            <syllab>ITI</syllab>
            <indice>52</indice>
        </entry>
        <entry>
            <syllab>iz</syllab>
            <indice>296</indice>
        </entry>
        <entry>
            <syllab>ka</syllab>
            <indice>15</indice>
        </entry>
        <entry>
            <syllab>KA</syllab>
            <indice>15</indice>
        </entry>
        <entry>
            <syllab>KÁ</syllab>
            <indice>133</indice>
        </entry>
        <entry>
            <syllab>KA₉</syllab>
            <indice>319</indice>
        </entry>
        <entry>
            <syllab>kál</syllab>
            <indice>343</indice>
        </entry>
        <entry>
            <syllab>KALAM</syllab>
            <indice>312</indice>
        </entry>
        <entry>
            <syllab>kam</syllab>
            <indice>406</indice>
        </entry>
        <entry>
            <syllab>KAM</syllab>
            <indice>406</indice>
        </entry>
        <entry>
            <syllab>kar</syllab>
            <indice>376</indice>
        </entry>
        <entry>
            <syllab>KAR</syllab>
            <indice>376</indice>
        </entry>
        <entry>
            <syllab>KAŠ</syllab>
            <indice>214</indice>
        </entry>
        <entry>
            <syllab>KAS₄</syllab>
            <indice>202</indice>
        </entry>
        <entry>
            <syllab>KASKAL</syllab>
            <indice>166</indice>
        </entry>
        <entry>
            <syllab>ke</syllab>
            <indice>461</indice>
        </entry>
        <entry>
            <syllab>KÉŠ</syllab>
            <indice>152</indice>
        </entry>
        <entry>
            <syllab>KÈŠ</syllab>
            <indice>546</indice>
        </entry>
        <entry>
            <syllab>ki</syllab>
            <indice>461</indice>
        </entry>
        <entry>
            <syllab>KI</syllab>
            <indice>461</indice>
        </entry>
        <entry>
            <syllab>KIB</syllab>
            <indice>228</indice>
        </entry>
        <entry>
            <syllab>KID</syllab>
            <indice>313</indice>
        </entry>
        <entry>
            <syllab>KIN</syllab>
            <indice>538</indice>
        </entry>
        <entry>
            <syllab>kir</syllab>
            <indice>346</indice>
        </entry>
        <entry>
            <syllab>KIR₄</syllab>
            <indice>15</indice>
        </entry>
        <entry>
            <syllab>KIRI₆</syllab>
            <indice>152</indice>
        </entry>
        <entry>
            <syllab>ku</syllab>
            <indice>536</indice>
        </entry>
        <entry>
            <syllab>KÙ</syllab>
            <indice>468</indice>
        </entry>
        <entry>
            <syllab>KU₅</syllab>
            <indice>12</indice>
        </entry>
        <entry>
            <syllab>kúl</syllab>
            <indice>429</indice>
        </entry>
        <entry>
            <syllab>kum</syllab>
            <indice>191</indice>
        </entry>
        <entry>
            <syllab>KUN</syllab>
            <indice>77</indice>
        </entry>
        <entry>
            <syllab>KUR</syllab>
            <indice>366</indice>
        </entry>
        <entry>
            <syllab>kur</syllab>
            <indice>366</indice>
        </entry>
        <entry>
            <syllab>KÚR</syllab>
            <indice>60</indice>
        </entry>
        <entry>
            <syllab>KÙŠ</syllab>
            <indice>318</indice>
        </entry>
        <entry>
            <syllab>KUŠ₇</syllab>
            <indice>212</indice>
        </entry>
        <entry>
            <syllab>LA</syllab>
            <indice>55</indice>
        </entry>
        <entry>
            <syllab>la</syllab>
            <indice>55</indice>
        </entry>
        <entry>
            <syllab>LÁ</syllab>
            <indice>481</indice>
        </entry>
        <entry>
            <syllab>LAH₄</syllab>
            <indice>206a</indice>
        </entry>
        <entry>
            <syllab>LAH₅</syllab>
            <indice>206</indice>
        </entry>
        <entry>
            <syllab>LAL</syllab>
            <indice>481</indice>
        </entry>
        <entry>
            <syllab>lam</syllab>
            <indice>435</indice>
        </entry>
        <entry>
            <syllab>le</syllab>
            <indice>59</indice>
        </entry>
        <entry>
            <syllab>li</syllab>
            <indice>59</indice>
        </entry>
        <entry>
            <syllab>lí</syllab>
            <indice>231</indice>
        </entry>
        <entry>
            <syllab>LIBIR</syllab>
            <indice>455</indice>
        </entry>
        <entry>
            <syllab>lik</syllab>
            <indice>575</indice>
        </entry>
        <entry>
            <syllab>LÍL</syllab>
            <indice>313</indice>
        </entry>
        <entry>
            <syllab>lim</syllab>
            <indice>449</indice>
        </entry>
        <entry>
            <syllab>liš</syllab>
            <indice>377</indice>
        </entry>
        <entry>
            <syllab>lu</syllab>
            <indice>537</indice>
        </entry>
        <entry>
            <syllab>LÚ</syllab>
            <indice>330</indice>
        </entry>
        <entry>
            <syllab>LUGAL</syllab>
            <indice>151</indice>
        </entry>
        <entry>
            <syllab>LUM</syllab>
            <indice>565</indice>
        </entry>
        <entry>
            <syllab>lum</syllab>
            <indice>565</indice>
        </entry>
        <entry>
            <syllab>ma</syllab>
            <indice>342</indice>
        </entry>
        <entry>
            <syllab>MA</syllab>
            <indice>342</indice>
        </entry>
        <entry>
            <syllab>MÁ</syllab>
            <indice>122</indice>
        </entry>
        <entry>
            <syllab>MAR</syllab>
            <indice>307</indice>
        </entry>
        <entry>
            <syllab>mar</syllab>
            <indice>307</indice>
        </entry>
        <entry>
            <syllab>maš</syllab>
            <indice>74</indice>
        </entry>
        <entry>
            <syllab>MÁŠ</syllab>
            <indice>76</indice>
        </entry>
        <entry>
            <syllab>me</syllab>
            <indice>532</indice>
        </entry>
        <entry>
            <syllab>ME</syllab>
            <indice>532</indice>
        </entry>
        <entry>
            <syllab>MES</syllab>
            <indice>314</indice>
        </entry>
        <entry>
            <syllab>MEŠ</syllab>
            <indice>533</indice>
        </entry>
        <entry>
            <syllab>mi</syllab>
            <indice>427</indice>
        </entry>
        <entry>
            <syllab>mil</syllab>
            <indice>212</indice>
        </entry>
        <entry>
            <syllab>MÌN</syllab>
            <indice>471</indice>
        </entry>
        <entry>
            <syllab>mu</syllab>
            <indice>61</indice>
        </entry>
        <entry>
            <syllab>MU</syllab>
            <indice>61</indice>
        </entry>
        <entry>
            <syllab>MUHALDIM</syllab>
            <indice>61</indice>
        </entry>
        <entry>
            <syllab>MUNU₄</syllab>
            <indice>60</indice>
        </entry>
        <entry>
            <syllab>MUNUS</syllab>
            <indice>554</indice>
        </entry>
        <entry>
            <syllab>mur</syllab>
            <indice>401</indice>
        </entry>
        <entry>
            <syllab>na</syllab>
            <indice>70</indice>
        </entry>
        <entry>
            <syllab>NA</syllab>
            <indice>70</indice>
        </entry>
        <entry>
            <syllab>NA₄</syllab>
            <indice>229</indice>
        </entry>
        <entry>
            <syllab>NAGAR</syllab>
            <indice>560</indice>
        </entry>
        <entry>
            <syllab>NAM</syllab>
            <indice>79</indice>
        </entry>
        <entry>
            <syllab>nam</syllab>
            <indice>79</indice>
        </entry>
        <entry>
            <syllab>NANŠE</syllab>
            <indice>200</indice>
        </entry>
        <entry>
            <syllab>ne</syllab>
            <indice>172</indice>
        </entry>
        <entry>
            <syllab>né</syllab>
            <indice>231</indice>
        </entry>
        <entry>
            <syllab>ni</syllab>
            <indice>231</indice>
        </entry>
        <entry>
            <syllab>NI</syllab>
            <indice>231</indice>
        </entry>
        <entry>
            <syllab>NÌ</syllab>
            <indice>597</indice>
        </entry>
        <entry>
            <syllab>ni₅</syllab>
            <indice>172</indice>
        </entry>
        <entry>
            <syllab>NIGIN</syllab>
            <indice>529</indice>
        </entry>
        <entry>
            <syllab>NIGIN₂</syllab>
            <indice>483</indice>
        </entry>
        <entry>
            <syllab>nim</syllab>
            <indice>433</indice>
        </entry>
        <entry>
            <syllab>NIM</syllab>
            <indice>433</indice>
        </entry>
        <entry>
            <syllab>NIN</syllab>
            <indice>556</indice>
        </entry>
        <entry>
            <syllab>NINA</syllab>
            <indice>200</indice>
        </entry>
        <entry>
            <syllab>NINDA</syllab>
            <indice>597</indice>
        </entry>
        <entry>
            <syllab>nu</syllab>
            <indice>75</indice>
        </entry>
        <entry>
            <syllab>NU</syllab>
            <indice>75</indice>
        </entry>
        <entry>
            <syllab>NUN</syllab>
            <indice>87</indice>
        </entry>
        <entry>
            <syllab>pa</syllab>
            <indice>295</indice>
        </entry>
        <entry>
            <syllab>PA₅</syllab>
            <indice>60a</indice>
        </entry>
        <entry>
            <syllab>pé</syllab>
            <indice>214</indice>
        </entry>
        <entry>
            <syllab>PI</syllab>
            <indice>383</indice>
        </entry>
        <entry>
            <syllab>pí</syllab>
            <indice>214</indice>
        </entry>
        <entry>
            <syllab>pi₄</syllab>
            <indice>15</indice>
        </entry>
        <entry>
            <syllab>pil</syllab>
            <indice>172</indice>
        </entry>
        <entry>
            <syllab>píl</syllab>
            <indice>173</indice>
        </entry>
        <entry>
            <syllab>pir</syllab>
            <indice>381</indice>
        </entry>
        <entry>
            <syllab>pu</syllab>
            <indice>371</indice>
        </entry>
        <entry>
            <syllab>pur</syllab>
            <indice>349</indice>
        </entry>
        <entry>
            <syllab>PUZUR₄</syllab>
            <indice>26</indice>
        </entry>
        <entry>
            <syllab>qa</syllab>
            <indice>62</indice>
        </entry>
        <entry>
            <syllab>qá</syllab>
            <indice>319</indice>
        </entry>
        <entry>
            <syllab>qar</syllab>
            <indice>3333</indice>
        </entry>
        <entry>
            <syllab>qé</syllab>
            <indice>461</indice>
        </entry>
        <entry>
            <syllab>qí</syllab>
            <indice>461</indice>
        </entry>
        <entry>
            <syllab>qú</syllab>
            <indice>536</indice>
        </entry>
        <entry>
            <syllab>qum</syllab>
            <indice>191</indice>
        </entry>
        <entry>
            <syllab>qúr</syllab>
            <indice>366</indice>
        </entry>
        <entry>
            <syllab>ra</syllab>
            <indice>328</indice>
        </entry>
        <entry>
            <syllab>RA</syllab>
            <indice>328</indice>
        </entry>
        <entry>
            <syllab>RÁ</syllab>
            <indice>206</indice>
        </entry>
        <entry>
            <syllab>re</syllab>
            <indice>86</indice>
        </entry>
        <entry>
            <syllab>RE</syllab>
            <indice>86</indice>
        </entry>
        <entry>
            <syllab>ri</syllab>
            <indice>86</indice>
        </entry>
        <entry>
            <syllab>ru</syllab>
            <indice>68</indice>
        </entry>
        <entry>
            <syllab>rum</syllab>
            <indice>1</indice>
        </entry>
        <entry>
            <syllab>sa</syllab>
            <indice>104</indice>
        </entry>
        <entry>
            <syllab>SA</syllab>
            <indice>104</indice>
        </entry>
        <entry>
            <syllab>SÁ</syllab>
            <indice>457</indice>
        </entry>
        <entry>
            <syllab>sà</syllab>
            <indice>586</indice>
        </entry>
        <entry>
            <syllab>ša</syllab>
            <indice>353</indice>
        </entry>
        <entry>
            <syllab>ŠÀ</syllab>
            <indice>384</indice>
        </entry>
        <entry>
            <syllab>ṣa</syllab>
            <indice>586</indice>
        </entry>
        <entry>
            <syllab>SA₁₂</syllab>
            <indice>115</indice>
        </entry>
        <entry>
            <syllab>SA₆</syllab>
            <indice>356</indice>
        </entry>
        <entry>
            <syllab>SAG</syllab>
            <indice>115</indice>
        </entry>
        <entry>
            <syllab>ŠAG₅</syllab>
            <indice>356</indice>
        </entry>
        <entry>
            <syllab>SAHAR</syllab>
            <indice>212</indice>
        </entry>
        <entry>
            <syllab>SANGA</syllab>
            <indice>314</indice>
        </entry>
        <entry>
            <syllab>šar</syllab>
            <indice>152</indice>
        </entry>
        <entry>
            <syllab>se</syllab>
            <indice>112</indice>
        </entry>
        <entry>
            <syllab>sé</syllab>
            <indice>84</indice>
        </entry>
        <entry>
            <syllab>SÈ</syllab>
            <indice>164</indice>
        </entry>
        <entry>
            <syllab>še</syllab>
            <indice>367</indice>
        </entry>
        <entry>
            <syllab>ŠE</syllab>
            <indice>367</indice>
        </entry>
        <entry>
            <syllab>ṣe</syllab>
            <indice>147</indice>
        </entry>
        <entry>
            <syllab>ṣé</syllab>
            <indice>84</indice>
        </entry>
        <entry>
            <syllab>ŠEŠ</syllab>
            <indice>331</indice>
        </entry>
        <entry>
            <syllab>si</syllab>
            <indice>112</indice>
        </entry>
        <entry>
            <syllab>SI</syllab>
            <indice>112</indice>
        </entry>
        <entry>
            <syllab>sí</syllab>
            <indice>84</indice>
        </entry>
        <entry>
            <syllab>ši</syllab>
            <indice>449</indice>
        </entry>
        <entry>
            <syllab>ṣí</syllab>
            <indice>84</indice>
        </entry>
        <entry>
            <syllab>SIG</syllab>
            <indice>592</indice>
        </entry>
        <entry>
            <syllab>SÍG</syllab>
            <indice>539</indice>
        </entry>
        <entry>
            <syllab>SIG₄</syllab>
            <indice>567</indice>
        </entry>
        <entry>
            <syllab>SIG₅</syllab>
            <indice>454</indice>
        </entry>
        <entry>
            <syllab>ṣíl</syllab>
            <indice>427</indice>
        </entry>
        <entry>
            <syllab>SILA₃</syllab>
            <indice>62</indice>
        </entry>
        <entry>
            <syllab>SIPA</syllab>
            <indice>295m</indice>
        </entry>
        <entry>
            <syllab>SÍR</syllab>
            <indice>371</indice>
        </entry>
        <entry>
            <syllab>SISKUR₂</syllab>
            <indice>696</indice>
        </entry>
        <entry>
            <syllab>su</syllab>
            <indice>7</indice>
        </entry>
        <entry>
            <syllab>SU</syllab>
            <indice>7</indice>
        </entry>
        <entry>
            <syllab>sú</syllab>
            <indice>6</indice>
        </entry>
        <entry>
            <syllab>šu</syllab>
            <indice>354</indice>
        </entry>
        <entry>
            <syllab>ŠU</syllab>
            <indice>354</indice>
        </entry>
        <entry>
            <syllab>ṣu</syllab>
            <indice>555</indice>
        </entry>
        <entry>
            <syllab>ṣú</syllab>
            <indice>6</indice>
        </entry>
        <entry>
            <syllab>ṣú</syllab>
            <indice>6</indice>
        </entry>
        <entry>
            <syllab>ŠUBUR</syllab>
            <indice>53</indice>
        </entry>
        <entry>
            <syllab>SUKKAL</syllab>
            <indice>321</indice>
        </entry>
        <entry>
            <syllab>ŠUKU</syllab>
            <indice>469</indice>
        </entry>
        <entry>
            <syllab>SUM</syllab>
            <indice>164</indice>
        </entry>
        <entry>
            <syllab>súm</syllab>
            <indice>555</indice>
        </entry>
        <entry>
            <syllab>šum</syllab>
            <indice>126</indice>
        </entry>
        <entry>
            <syllab>ṣum</syllab>
            <indice>555</indice>
        </entry>
        <entry>
            <syllab>SUMUN</syllab>
            <indice>69</indice>
        </entry>
        <entry>
            <syllab>šur</syllab>
            <indice>101</indice>
        </entry>
        <entry>
            <syllab>ṣur</syllab>
            <indice>437</indice>
        </entry>
        <entry>
            <syllab>ta</syllab>
            <indice>139</indice>
        </entry>
        <entry>
            <syllab>TA</syllab>
            <indice>139</indice>
        </entry>
        <entry>
            <syllab>ṭa</syllab>
            <indice>335</indice>
        </entry>
        <entry>
            <syllab>ṭá</syllab>
            <indice>139</indice>
        </entry>
        <entry>
            <syllab>ṭà</syllab>
            <indice>396</indice>
        </entry>
        <entry>
            <syllab>tah</syllab>
            <indice>169</indice>
        </entry>
        <entry>
            <syllab>ták</syllab>
            <indice>280</indice>
        </entry>
        <entry>
            <syllab>TAM</syllab>
            <indice>381</indice>
        </entry>
        <entry>
            <syllab>tam</syllab>
            <indice>381</indice>
        </entry>
        <entry>
            <syllab>tap</syllab>
            <indice>129</indice>
        </entry>
        <entry>
            <syllab>tar</syllab>
            <indice>12</indice>
        </entry>
        <entry>
            <syllab>tár</syllab>
            <indice>114</indice>
        </entry>
        <entry>
            <syllab>ṭar</syllab>
            <indice>12</indice>
        </entry>
        <entry>
            <syllab>te</syllab>
            <indice>172</indice>
        </entry>
        <entry>
            <syllab>ṭe</syllab>
            <indice>457</indice>
        </entry>
        <entry>
            <syllab>ṭe₄</syllab>
            <indice>172</indice>
        </entry>
        <entry>
            <syllab>te₉</syllab>
            <indice>73</indice>
        </entry>
        <entry>
            <syllab>tel</syllab>
            <indice>69</indice>
        </entry>
        <entry>
            <syllab>ter</syllab>
            <indice>375</indice>
        </entry>
        <entry>
            <syllab>ti</syllab>
            <indice>73</indice>
        </entry>
        <entry>
            <syllab>ṭi</syllab>
            <indice>457</indice>
        </entry>
        <entry>
            <syllab>ṭì</syllab>
            <indice>73</indice>
        </entry>
        <entry>
            <syllab>TIBIRA</syllab>
            <indice>132</indice>
        </entry>
        <entry>
            <syllab>TIL</syllab>
            <indice>69</indice>
        </entry>
        <entry>
            <syllab>til</syllab>
            <indice>69</indice>
        </entry>
        <entry>
            <syllab>tim</syllab>
            <indice>94</indice>
        </entry>
        <entry>
            <syllab>TIR</syllab>
            <indice>375</indice>
        </entry>
        <entry>
            <syllab>tu</syllab>
            <indice>58</indice>
        </entry>
        <entry>
            <syllab>TU</syllab>
            <indice>58</indice>
        </entry>
        <entry>
            <syllab>ṭú</syllab>
            <indice>58</indice>
        </entry>
        <entry>
            <syllab>TÚG</syllab>
            <indice>536</indice>
        </entry>
        <entry>
            <syllab>TUKUL</syllab>
            <indice>536</indice>
        </entry>
        <entry>
            <syllab>TÚL</syllab>
            <indice>511</indice>
        </entry>
        <entry>
            <syllab>ṭul</syllab>
            <indice>511</indice>
        </entry>
        <entry>
            <syllab>TUM</syllab>
            <indice>207</indice>
        </entry>
        <entry>
            <syllab>tum</syllab>
            <indice>207</indice>
        </entry>
        <entry>
            <syllab>ṭup</syllab>
            <indice>138</indice>
        </entry>
        <entry>
            <syllab>TUR</syllab>
            <indice>144</indice>
        </entry>
        <entry>
            <syllab>u</syllab>
            <indice>411</indice>
        </entry>
        <entry>
            <syllab>U</syllab>
            <indice>411</indice>
        </entry>
        <entry>
            <syllab>Ú</syllab>
            <indice>318</indice>
        </entry>
        <entry>
            <syllab>ú</syllab>
            <indice>318</indice>
        </entry>
        <entry>
            <syllab>Ù</syllab>
            <indice>455</indice>
        </entry>
        <entry>
            <syllab>ù</syllab>
            <indice>455</indice>
        </entry>
        <entry>
            <syllab>U₄</syllab>
            <indice>381</indice>
        </entry>
        <entry>
            <syllab>u₄</syllab>
            <indice>381</indice>
        </entry>
        <entry>
            <syllab>U₈</syllab>
            <indice>494</indice>
        </entry>
        <entry>
            <syllab>ub</syllab>
            <indice>306</indice>
        </entry>
        <entry>
            <syllab>ud</syllab>
            <indice>381</indice>
        </entry>
        <entry>
            <syllab>UD</syllab>
            <indice>381</indice>
        </entry>
        <entry>
            <syllab>UDU</syllab>
            <indice>537</indice>
        </entry>
        <entry>
            <syllab>UGULA</syllab>
            <indice>295</indice>
        </entry>
        <entry>
            <syllab>uh</syllab>
            <indice>398</indice>
        </entry>
        <entry>
            <syllab>ÚH</syllab>
            <indice>392</indice>
        </entry>
        <entry>
            <syllab>úh</syllab>
            <indice>392</indice>
        </entry>
        <entry>
            <syllab>uk</syllab>
            <indice>130</indice>
        </entry>
        <entry>
            <syllab>ul</syllab>
            <indice>441</indice>
        </entry>
        <entry>
            <syllab>um</syllab>
            <indice>134</indice>
        </entry>
        <entry>
            <syllab>un</syllab>
            <indice>312</indice>
        </entry>
        <entry>
            <syllab>UN</syllab>
            <indice>312</indice>
        </entry>
        <entry>
            <syllab>UNU</syllab>
            <indice>195</indice>
        </entry>
        <entry>
            <syllab>up</syllab>
            <indice>306</indice>
        </entry>
        <entry>
            <syllab>uq</syllab>
            <indice>130</indice>
        </entry>
        <entry>
            <syllab>ur</syllab>
            <indice>575</indice>
        </entry>
        <entry>
            <syllab>UR</syllab>
            <indice>575</indice>
        </entry>
        <entry>
            <syllab>úr</syllab>
            <indice>203</indice>
        </entry>
        <entry>
            <syllab>URTA</syllab>
            <indice>575</indice>
        </entry>
        <entry>
            <syllab>us</syllab>
            <indice>372</indice>
        </entry>
        <entry>
            <syllab>uš</syllab>
            <indice>211</indice>
        </entry>
        <entry>
            <syllab>uṣ</syllab>
            <indice>372</indice>
        </entry>
        <entry>
            <syllab>ús</syllab>
            <indice>211</indice>
        </entry>
        <entry>
            <syllab>ÚS</syllab>
            <indice>211</indice>
        </entry>
        <entry>
            <syllab>úš</syllab>
            <indice>69</indice>
        </entry>
        <entry>
            <syllab>USAN₃</syllab>
            <indice>394c</indice>
        </entry>
        <entry>
            <syllab>ut</syllab>
            <indice>381</indice>
        </entry>
        <entry>
            <syllab>uṭ</syllab>
            <indice>381</indice>
        </entry>
        <entry>
            <syllab>UTU</syllab>
            <indice>381</indice>
        </entry>
        <entry>
            <syllab>uz</syllab>
            <indice>372</indice>
        </entry>
        <entry>
            <syllab>ÙZ</syllab>
            <indice>122b</indice>
        </entry>
        <entry>
            <syllab>wa</syllab>
            <indice>383</indice>
        </entry>
        <entry>
            <syllab>we</syllab>
            <indice>383</indice>
        </entry>
        <entry>
            <syllab>wi</syllab>
            <indice>383</indice>
        </entry>
        <entry>
            <syllab>wu</syllab>
            <indice>383</indice>
        </entry>
        <entry>
            <syllab>ya</syllab>
            <indice>383</indice>
        </entry>
        <entry>
            <syllab>yi</syllab>
            <indice>383</indice>
        </entry>
        <entry>
            <syllab>yu</syllab>
            <indice>383</indice>
        </entry>
        <entry>
            <syllab>za</syllab>
            <indice>586</indice>
        </entry>
        <entry>
            <syllab>ZA</syllab>
            <indice>586</indice>
        </entry>
        <entry>
            <syllab>ZAL</syllab>
            <indice>231</indice>
        </entry>
        <entry>
            <syllab>ze</syllab>
            <indice>84</indice>
        </entry>
        <entry>
            <syllab>ZI</syllab>
            <indice>84</indice>
        </entry>
        <entry>
            <syllab>zi</syllab>
            <indice>84</indice>
        </entry>
        <entry>
            <syllab>ZÌ</syllab>
            <indice>536</indice>
        </entry>
        <entry>
            <syllab>zu</syllab>
            <indice>6</indice>
        </entry>
        <entry>
            <syllab>ZU</syllab>
            <indice>6</indice>
        </entry>
        <entry>
            <syllab>ZÚ</syllab>
            <indice>15</indice>
        </entry>
    </xsl:variable>
    <!-- to externalize in a document : -->
    <!--<xsl:variable name="syllabary" select="document('syllabary.xml')" />-->

    <!-- phases call -->
    <xsl:template match="/">
        <xsl:variable name="intermediate">
            <xsl:apply-templates mode="phase1"/>
        </xsl:variable>
        <xsl:apply-templates select="$intermediate" mode="phase2"/>
    </xsl:template>

    <!-- phase 1 -->
    <xsl:template match="w/text()" mode="phase1">
        <xsl:param name="separator" select="'-|\.|\s'"/>
        <xsl:for-each select="tokenize(replace(., '\(.*?\)', '-$0-'), $separator)[.]">
            <g>
                <xsl:value-of select="normalize-space(.)"/>
            </g>
        </xsl:for-each>
    </xsl:template>

    <!-- phase 2 -->
    <xsl:template match="g" mode="phase2">
        <xsl:variable name="syllab" select="./text()"/>
        <xsl:copy>
            <xsl:attribute name="ref" select="normalize-space(
                concat('#MesZL', $syllabary/entry[syllab/text() = $syllab]/indice)
                )"/>
            <xsl:value-of select="."/>
        </xsl:copy>
    </xsl:template>

    <!-- identity copy -->
    <xsl:template match="node()|@*" mode="#all">
        <xsl:copy>
            <xsl:apply-templates select="node()|@*" mode="#current"/>
        </xsl:copy>
    </xsl:template>

</xsl:stylesheet>
